zinza-d2-training/lms-system

.github/dependabot.yml
.github/pull_request_template.md
.github/workflows/ci.yml

Add github Merge request template and Ci

Add Github workflow and template

---

package.json
src/App.test.tsx
src/App.tsx
src/components/Forgotpassword/Forgotpassword.tsx
src/components/Forgotpassword/forgotpassword.scss
src/components/Header/Header.tsx
yarn.lock

Add Forgot password page

---

src/components/Home/Home.tsx
src/components/Layout/Content/BreadCrumb.tsx
src/components/Layout/Content/MainContent.tsx

– change height main content
- change padding maincontent

fix padding content

---

src/components/ForgotPassword/ForgotPassword.css
src/components/ForgotPassword/ForgotPassword.tsx
src/components/ForgotPassword/forgotPassword.scss
src/components/ResetPassword/ResetPassword.css

Update content and css form forgotPassword

---

src/App.tsx
src/components/common/PrivateRoute.tsx
src/services/AuthService.ts

Fix Maximum update render issue

---

package.json
src/App.tsx
src/components/Courses/CourseDetail.tsx
src/components/ManagerFiles/ManagerFiles.tsx
src/components/ManagerFiles/UploadFile.tsx
src/components/ManagerFiles/UploadFileLink.tsx
src/components/ManagerFiles/hook.ts
src/fakeData/files.ts
src/services/FileService.ts
src/types/files.ts
yarn.lock

Impelment manager files

---

package.json
src/App.tsx
src/components/Contents/AddContent/AudioContent.tsx
src/components/Contents/AddContent/BasicContent.tsx
src/components/Contents/AddContent/IframeContent.tsx
src/components/Contents/AddContent/Survey.tsx
src/components/Contents/AddContent/VideoContent.tsx
src/components/Contents/AddContent/WebContent.tsx
src/components/Contents/AddContent/index.tsx
src/components/Contents/Contents.tsx
src/components/Contents/hook.ts
src/components/Courses/CourseDetail.tsx
src/services/ContentService.ts
src/types/contents.ts
yarn.lock

Add edit content Routes and Structure

---

src/App.tsx
src/components/Courses/index.tsx
src/components/Discussions/Discussion.tsx
src/components/Discussions/DiscussionDetail.tsx
src/components/Discussions/DiscussionForm.tsx
src/components/Discussions/DiscussionList.tsx
src/components/Discussions/hook.ts
src/components/Discussions/style.css
src/fakeData/comments.ts
src/fakeData/discussion.ts
src/services/DiscussionService.ts
src/types/discussions.ts

Implement discussion layout

---

src/components/Discussions/CommentForm.tsx
src/components/Discussions/DiscussionDetail.tsx
src/components/Discussions/hook.ts
src/fakeData/comments.ts
src/fakeData/discussion.ts
src/services/DiscussionService.ts
src/types/discussions.ts

Implement discussion detail

---

src/components/Contents/AddContent/MainContent/StyleTabBasicContent.css
src/components/Contents/ViewContent/ViewContents.tsx
src/fakeData/contents.ts

Feature 58 View Content Audio

---

src/App.tsx
src/components/Contents/ViewContent/NavigateContents.tsx
src/components/Contents/ViewContent/ViewContents.tsx
src/components/Courses/hook.ts
src/components/Courses/index.tsx
src/fakeData/contents.ts
src/services/ContentService.ts

Feature 59 View Course-Video

---

src/components/Contents/AddContent/MainContent/IFrameContent/IframeContent.tsx
src/components/Contents/AddContent/MainContent/StyleTabBasicContent.css
src/components/Contents/ViewContent/ViewContents.tsx
src/fakeData/contents.ts

Feature 62 view Course Iframe

---

src/components/Contents/ViewContent/SurveyResponseFinalForm.tsx
src/components/Contents/ViewContent/ViewContents.tsx
src/components/Contents/ViewContent/ViewSurveysContent.tsx
src/components/Contents/ViewContent/hook.ts
src/fakeData/contents.ts
src/fakeData/questions.ts
src/fakeData/surveyResponses.ts
src/services/SurveyResponseService.ts
src/types/questions.ts

Success implement_course_survey

---

src/components/Contents/AddContent/MainContent/IFrameContent/IframeContent.tsx
src/components/Contents/AddContent/Survey/Survey.tsx
src/components/Contents/AddContent/Survey/SurveyQuestionListFinalForm.tsx
src/components/Courses/CourseDetail.tsx
src/components/Courses/CourseInfoDialog.tsx
src/components/Courses/Courses.css
src/components/Courses/ListCourses/ListCourses.tsx
src/components/Courses/index.tsx
src/components/Layout/Header/Header.tsx
src/components/Login/Login.tsx

Fix role for learner

---

src/App.tsx
src/components/Contents/AddContent/MainContent/IFrameContent/IframeContent.tsx
src/components/Courses/ListCourses/ListCourses.tsx
src/components/Courses/ListCourses/MenuActions.tsx
src/components/Layout/Header/Header.tsx
src/components/Signup/Signup.tsx
src/components/UserProfile/Info/StyleUserInfo.css
src/components/UserProfile/Info/UserCourses.tsx
src/components/UserProfile/Info/UserFiles.tsx
src/components/UserProfile/Info/UserInfor.tsx
src/components/UserProfile/Info/hook.ts
src/components/UserProfile/Info/index.tsx
src/fakeData/courses.ts
src/fakeData/files.ts
src/fakeData/users.ts
src/services/AuthService.ts
src/services/ContentService.ts
src/services/CourseService.ts
src/services/FileService.ts
src/types/courses.ts
src/types/files.ts
src/types/users.ts

Feature 63 Implement User Info

---

src/components/Layout/Header/Header.tsx
src/contexts/UserContext.tsx
src/services/AuthService.ts
src/types/users.ts
src/utils/axios.ts

Fix 77 Axios Client

---

package.json
src/App.tsx
src/components/ForgotPassword/ForgotPassword.tsx
src/components/Login/Login.tsx
src/components/ResetPassword/ResetPassword.tsx
src/components/Signup/Signup.tsx
src/services/AuthService.ts
src/utils/axios.ts
yarn.lock

Auth Module with Api

---

src/components/Courses/CourseDetail.tsx
src/components/Courses/CourseForm.tsx
src/components/Courses/CourseInfoDialog.tsx
src/components/Courses/ListCourses/ListCourses.tsx
src/components/Courses/hook.ts
src/components/Courses/index.tsx
src/components/Pagination/index.tsx
src/components/common/ImageField.tsx
src/contexts/UserContext.tsx
src/fakeData/courses.ts
src/services/CourseService.ts
src/types/courses.ts
src/utils/formatUrl.ts
src/utils/urlHelper.ts

– List user course
- Add course
- Detail course
- Update course

Connect course api

---

src/components/Courses/CourseForm.tsx
src/components/Courses/Courses.css
src/components/Courses/ListCourses/ListCourses.tsx
src/components/Courses/index.tsx
src/components/UserProfile/Info/UserInfor.tsx
src/components/common/ImageField.tsx
src/fakeData/courses.ts
src/types/courses.ts

Fix 79 Update Image

---

src/components/Contents/AddContent/MainContent/MainContent.tsx
src/components/Contents/AddContent/Survey/Survey.tsx
src/components/Contents/ViewContent/ViewContents.tsx
src/components/Contents/ViewContent/ViewSurveysContent.tsx
src/components/Contents/hook.ts
src/components/Courses/CourseDetail.tsx
src/components/Courses/CourseForm.tsx
src/components/Courses/CourseInfoDialog.tsx
src/components/Courses/hook.ts
src/components/Courses/index.tsx
src/services/ContentService.ts
src/services/CourseService.ts

Connect content api
